### ISSUE TITLE
Load comments in Descending Order

### ISSUE THREAD

**Issue by blazer2k1** [jdvp/jekyll-comments-google-forms#6]
as per title, including replies.

**Comment by jdvp** [comment]
@blazer2k1 pretty sure you can already do this, set the chunk size to a positive number. See the "chunk size" section in this article:

https://jdvp.me/articles/Google-Forms-Jekyll-Comments-Revisited

**Comment by blazer2k1** [comment]
Yes, I did miss that part, thanks!

**Comment by blazer2k1** [comment]
@jdvp  to follow-up, when setting to a positive number like `hiddenComments.slice(5)`, it only works when `chunk_comment_loading` AND `lazy_load_comments` are set to `true`, but it only displays the recent slice with the button clickable only on this first load.

**Comment by jdvp** [comment]
@blazer2k1 what settings are you personally trying to achieve? with/without chunked comments, with/without lazy loading etc?

It's been a while but I'll play around and try to get you what you want. Might update it to be a configurable option but I'll wanna see complexity first haha

**Comment by blazer2k1** [comment]
It would be nice to have all options, just like what it is in ascending order, right? 

Anyway for starters I figured out this part works so far by changing 2 lines with `sort` to `b to a` timestamp without changing the slice to positive, since it was problematic:

```
.sort((a, b) => (new Date(b.timestamp).getTime() || 0) - (new Date(a.timestamp).getTime()
...
...
.sort((a, b) => (new Date(b.timestamp).getTime() || 0) - (new Date(a.timestamp).getTime() || 0))
```

This works on lazy load comments and chunk comments set either to true or false.

the only issue now is loading chunk comments at the bottom instead on top.

**Comment by jdvp** [comment]
actually im mega confused what you want now lol

making the change you've mentioned above works as expected to me and chunking also works as expected? if the very oldest item is at the bottom, the chunks have to populate in at the top in order to make the items stay in the correct order chronologically?

For example 
| | before clicking load more | after |
|----| ---- | ---- |
|image |<img width="600" alt="Screenshot 2023-09-28 at 10 50 12 PM" src="https://github.com/jdvp/jekyll-comments-google-forms/assets/7111196/1d9ca5ce-ede1-4c57-b6b3-71ed325f33c3"> | <img width="600" alt="Screenshot 2023-09-28 at 10 50 24 PM" src="https://github.com/jdvp/jekyll-comments-google-forms/assets/7111196/3af49a4b-531e-4a01-98d4-cb597a1d85b8"> |
| comment order chronologically | 3<br>2<br>1 | 6<br>5<br>4<br>3<br>2<br>1 |

**Comment by blazer2k1** [comment]
No, with the 2 line change I posted, when you set chunk comments to true, the latest is loaded first which is correct, then when you click load more it is supposed to be loaded at the bottom since the next set is older.

so when page is loaded this is currently what happens: ✔
6
5
4

then when clicking load more: ❌
3
2
1
6
5
4

It should have something to do with the default ascending order you set where the newer is loaded at the top that needs to change according to this descending order set up

**Comment by jdvp** [comment]
i have those changes locally and i am seeing the behavior into the screenshot as indicated in the table I have provided (code changed on my end: https://github.com/jdvp/jekyll-comments-google-forms/commit/13faf74c6f5bc1262d6032f029c6f37a0c20996a)

**Comment by jdvp** [comment]
My main confusion here lies in the fact that, if we disregard chunking entirely, by default the comments are in ascending order by timestamp so that the oldest comment will be the first one at the top of the list as you scroll down.

Reversing the order to have it in descending order would mean that the very first comment you see is the newest comment as you scroll down the page.

The intention of chunked comments in this library is to show the last x elements in the list (whether ascending or descending and show those). Therefore, clicking the more button should always show more elements above the ones are displayed


In your example that you've given:

> so when page is loaded this is currently what happens: ✔
6
5
4

this is the default order. The oldest comment is at the top. If it were in descending order it would be at the bottom. 

I am willing to make the changes I've provided in the latest commit to allow reversing of the list easily but I don't think I am willing to make any updates to the chunking behavior directly. In the first place, a lot of the intention of adding the code to github was so that others could find it and modify as they want

**Comment by jdvp** [comment]
But anyway, I _think_ what you want can be achieved by changing

```
newCommentsToDisplay.reverse().forEach(element => displaySingleComment(element, true));
```

to

```
newCommentsToDisplay.reverse().forEach(element => displaySingleComment(element, false);
```

? Like without all the other changes we talked about. I might still be wrong about understanding the requirements here though 😓 

anyway sorry if i'm coming off as a little cranky, pretty long day on my end lol

**Comment by blazer2k1** [comment]
No worries, I did figure out that part just earlier with the `displaySingleComment` line. 

I'm also currently checking your latest changes and new branch about this issue.

Thanks and be right back.

**Comment by blazer2k1** [comment]
Ok I got it working now with some minor changes to your new branch solution. 

Basically I just moved the comment section below so now the texbox is on top and hook the scrolling to the total post only for loading more comments button.

Which I had to set: `netNewComments.forEach(element => displaySingleComment(element, true));`
so new comments posted will just pop below the textbox and not scroll to the bottom.

Thanks again. 👍
